spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database : testdb
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379


logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

